title: "Natron"
description: Open Source Compositing Software For VFX and Motion Graphics
# Build settings
sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: "true"
  input: GFM
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections_dir: _collections
collections:
  features:
    output: true
    permalink: /features/:path/
plugins:
  - jekyll-feed
  - jekyll-redirect-from