title: "Natron"
description: Open Source VFX Compositing Software
url: "https://natrongithub.github.io"
# Baseurl needed for some plugins to work correctly
baseurl: ""
twitter: https://twitter.com/natronvfx
discord: https://discord.gg/cpMj5p3Fv5
forum: https://discuss.pixls.us/c/software/natron
github: https://github.com/NatronGitHub/Natron
# Build settings
sass:
  style: compressed
markdown: kramdown
kramdown:
  auto_ids: "true"
  input: GFM
  syntax_highlighter_opts:
    default_lang: python
    css_class: 'highlight'
    span:
      line_numbers: false
    block:
      line_numbers: true
      start_line: 1
collections_dir: site_collections
collections:
  features:
    output: true
    permalink: /features/:path/
  posts:
    output: true
    permalink: news/:path/
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-relative-urls